# Generated by Django 4.0.5 on 2022-06-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='NomeEditora',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
