# Generated by Django 4.0.5 on 2022-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autor_options_livros'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='autor',
            field=models.ManyToManyField(related_name='livros', to='core.autor'),
        ),
    ]
