# Generated by Django 4.0.5 on 2022-06-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itenscompra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
