# Generated by Django 4.0.5 on 2022-06-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_livros_livro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'autores'},
        ),
    ]
